### ISSUE TITLE
Possible solution regex problem in generic parser

### ISSUE THREAD

**Issue by eminks** [ahmetb/baklava#11]
I think we can solve this issue by deleting"." and "," in the string. I tried a little bit and it seems working normal and no problem with 4 digits prices.

I tried changing part of code to this;
```
t = strings.ReplaceAll(t, ".", "")
t = strings.ReplaceAll(t, ",", "")
price, err := strconv.ParseInt(t, 10, 64)
if err != nil {
	return nil, fmt.Errorf("error transforming string to integer (from %v): %v", t, err)
}

return money.New(price, currency), nil
```

Original code;
https://github.com/ahmetb/baklava/blob/1dbca945f30cbe4e585ba4905f9d9ecad8f37e35/providers/genericparser/base.go#L64C1-L77C49

**Comment by ahmetb** [comment]
Write unit tests please. :)
